// Snapshot from "Запись 2026" sheet, column E (Машина), deduped case-insensitively
// and trimmed. Refresh by re-exporting from the sheet when the list drifts.
export const CAR_SUGGESTIONS: readonly string[] = Object.freeze([
  'Купе',
  'Москвич',
  'Москвич 6',
  'Мот',
  'Мотоцикл',
  'Хончи',
  'Эвакуатор',
  'Aito Seres M5',
  'Aito Seres M7',
  'Audi A3',
  'Audi A4',
  'Audi a5',
  'Audi A6',
  'Audi A7',
  'Audi q3',
  'Belgee S50',
  'Belgee X50',
  'Belgee X70',
  'Bestune b70',
  'BMW',
  'BMW 3',
  'BMW 3 G20',
  'BMW 4',
  'BMW 5',
  'BMW 6',
  'BMW 7',
  'BMW E60',
  'BMW g30',
  'BMW X4',
  'BMW X5',
  'BMW X6',
  'BMW X7',
  'Chery Tiggo',
  'Chery Tiggo 4',
  'Chevrolet Cruze',
  'Citroen C5',
  'Denzo N9',
  'Dodge Charger',
  'Evolute i-space',
  'Exeed TXL',
  'Exlantic',
  'Exlantic ET',
  'Exlantix ET',
  'Ford Bronko',
  'Ford Fiesta',
  'Ford Focus',
  'Ford Focus 3',
  'Ford kuga',
  'Gac Gs8',
  'Gac M8',
  'Geely Atlas',
  'Geely coolray',
  'Geely Ex-5',
  'Geely ex-5m',
  'Geely EX5 EM-I',
  'Geely EX5 Emi',
  'Geely Monjaro',
  'Geely Preface',
  'Gelly Atlas',
  'Genesis GV80',
  'Haval',
  'Haval Dargo',
  'Haval F7',
  'Haval H6',
  'Haval H9',
  'Haval Julion',
  'Honda Civic',
  'Honda CR-V',
  'Honda Pilot',
  'Honda Tribute',
  'hongqi hs5',
  'Hyndai Creta',
  'Hyndai Polisad',
  'Hyndai Santa Fe',
  'Hyndai Solaris',
  'Hyundai creta',
  'Hyundai Elantra',
  'Hyundai Gets',
  'Hyundai Grand Starex',
  'Hyundai polisad',
  'Hyundai Santafe',
  'Hyundai Solaris',
  'Hyundai Sonata',
  'Hyundai Staria',
  'Hyundai Tucson',
  'Infiniti qx70',
  'Jac',
  'Jac J7',
  'Jac T9',
  'Jaecoo J7',
  'Jaguar XE',
  'Jaguar XF',
  'Jeep Grand Cherokee',
  'Jeour X70+',
  'Jetour',
  'Jetour Dashing',
  'Jetour T1',
  'Jetour X70+',
  'Jetta VS7',
  'Kia Ceed',
  'Kia Cerato',
  'Kia K5',
  'Kia K900',
  'Kia Optima',
  'Kia Rio',
  'Kia Rio X',
  'Kia Soul',
  'Lada Granta',
  'Lada Largus',
  'Lada Vesta',
  'Lada Vesta SW',
  'LC Prado',
  'LC200',
  'Li 6',
  'Li l9',
  'Lixiang L7',
  'LR RR 21',
  'Lynk&Co 08',
  'Lynk&Co 900',
  'Mazda',
  'Mazda CX-3',
  'Mazda cx-5',
  'Mazda CX5',
  'MB',
  'MB 412',
  'MB B',
  'MB C',
  'MB C 204',
  'MB C180',
  'MB Cla',
  'MB E',
  'MB E-coupe',
  'MB GL',
  'MB GLE',
  'MB GLK',
  'MB GLS',
  'MB V class',
  'Mitsu Delica',
  'Mitsu Outlander',
  'Nissan Cube',
  'Nissan X-trail',
  'Niva Legend',
  'Niva Travel',
  'Omoda C5',
  'Opel Astra',
  'Opel Zafira',
  'Porsche Cayenne',
  'Qiyuan a06',
  'Ram 1500',
  'Renauilt Fluence',
  'Renault Arkana',
  'Renault Duster',
  'Renault Koleos',
  'Renault Logan',
  'Renault lotitud',
  'Renault Megan',
  'Renualt Duster',
  'Skoda Karoq',
  'Skoda Kodiaq',
  'Skoda Octavia',
  'Skoda Superb',
  'Suzuki Grand Vitara',
  'Suzuki Splash',
  'Tank 300',
  'Tank 700',
  'Tank500',
  'Tenet T4',
  'Tenet t7',
  'Toyota Camry',
  'Toyota Corolla',
  'Toyota LC',
  'Toyota LC 100',
  'Toyota Rav4',
  'Toyota Verso',
  'Voah Dream',
  'Volvo S60',
  'Voyah Free',
  'VW Tayron',
  'VW Tiguan',
  'VW Toureg',
  'Yangwang U8',
])
